name: Terraform

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.1
    -
      name: Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    -
      name: Init
      id: init
      run: terraform init -input=false
    -
      name: Validate
      id: validate
      run: terraform validate -no-color
    -
      name: Test
      id: test
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform test -no-color
