name: tfsec

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  tfsec:
    name: sarif report
    runs-on: ubuntu-20.04

    steps:
    - name: Clone repo
      uses: actions/checkout@master

    - name: tfsec
      uses: aquasecurity/tfsec-sarif-action@v0.1.0
      with:
        sarif_file: tfsec.sarif

    - name: Upload
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: tfsec.sarif
